name: On Pull Request Opened
on:
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  lint:
    name: Lint Debug
    uses: ./.github/workflows/lint.yml
  test:
    name: Test Debug
    needs: lint
    uses: ./.github/workflows/test.yml
